### ISSUE TITLE
Support missing for AOSP Email

### ISSUE THREAD

**Issue by ghost** [SpiritCroc/DarkCroc-Android-theme#10]
I just moved from "Default Dark Theme..." to "DarkCroc-Android..." because I upgraded my phone from Nougat to Pie. Unfortunately this theme does not seem to have support for the AOSP email app. Any plans to change that in the future? It would be terrific to keep this excellent theme on top of the line! Thanks, Baer

**Comment by SpiritCroc** [comment]
Great to hear you like my theme!

I have dropped support for AOSP Email because of following reasons:
- I don't use it anymore (I found out that K-9 Mail has a good material dark design when building from source, unfortunately they still haven't released builds with material design publicly it seems)
- AOSP Mail has many theming issues, i.e. hardcoded colors that can't be changed without changing the source code (even more when using the tablet layout than the phone one). While I did some adaptions to the app for AICP in the past, this also means that it will look different depending on whether you have the "improved" app or not. Most ROMs tend to use the unmodified AOSP app. I came to the conclusion that I'm not really happy with the dark theme I can provide for this app because of that.
- It looks to me like the AOSP Email app is not actively developped. For that reason, it would likely work for you to use the Default Dark Theme overlay for Email and get the same result as if I included it in DarkCroc.

**Comment by ghost** [comment]
Thank you for providing insight on the problems with Android's stock email app. I followed your advice and use the overlay from the default dark theme for email while using the new DarkCroc theme for everyhing else (running Resurrection Remix 7.0.2).
