### ISSUE TITLE
Pixel-like colours

### ISSUE THREAD

**Issue by bjasi** [SpiritCroc/DarkCroc-Android-theme#11]
Hi, do you think you could add colours like in Pixel phones, Google Apps and in AOSP?
- pale blue used in Google apps dark mode: 8AB4F8
- dark blue also used there: 2EC9C1
- normal Pixel blue: 1A73E8
- AOSP teal: 258982
It would be nice for consistent look with apps that don't use system colours

**Comment by bjasi** [comment]
They have also named similar colours Blue A100, Blue 800 and Blue A400 respectively (teal doesn't have one) but original colours would be better

**Comment by SpiritCroc** [comment]
Hi, so it would be fine if I add a user accent that uses the pixel color values you suggested, or do you want separate selections for each of those?
Where does your value for "AOSP teal" come from? It does not match either the dark or light teal used in AOSP to my knowledge. So do I understand correctly that you want an extra accent color choice for AOSP teal? The teal used by AOSP in dark themes is already included, but not the one used in light themes, since I don't like it when used in combination with dark themes (which doesn't mean that I can't add it if there is demand, but the correct hex would be #008577).

I'm also not sure if your pixel values are correct, your "dark blue" looks more like turqoise or cyan to me.

**Comment by bjasi** [comment]
Hi, I got the "Pixel colours" from Google contacts and messaging apps. My teal colour came from some accent changing Magisk module, the creator probably didn't know the exact value, but #008577 is very similar and it would be nice to have a darker teal too (this one you suggested).

I checked it now and I got two different values for pale blue from different apps. So Blue A100 #82B1FF seems correct (also mentioned Magisk module uses it). That dark blue was some mistake. The actual value is #185ABC (taken from Messages and Phone pill buttons) it can be also replaced by named Blue 800 #1565C0

**Comment by bjasi** [comment]
The previously mentioned I am most interested in. Then Pixel blue might be also good, but I'm not sure if it is used with dark backgrounds, in apps I have it is usually replaced by pale or dark blue. I'm also not sure what the hex is. In current Google Apps it is #1A73E8.

**Comment by SpiritCroc** [comment]
Could you maybe list your exact accent wishes again so I can be sure I understood them correctly?
e.g.
accent name 1: accent hex for dark themes: hex1, accent hex for light themes: hex2

**Comment by bjasi** [comment]
Blue A100 (or pale blue): #82B1FF
Dark blue: #185ABC
dark teal: #008577
all for dark themes

_(For your consideration:
You seem to prefer using named colours. If you want, you can use this alternative. It's upon you, I'm OK with both:
Blue A100 (or pale blue): #82B1FF
Blue 800: #1565C0
Teal 600: #00897B)_

**Comment by bjasi** [comment]
_For your consideration:
You seem to prefer to use named colours. If you want, you can use this alternative:
Blue A100 (or pale blue): #82B1FF
Blue 800: #1565C0
Teal 600: #00897B_

**Comment by SpiritCroc** [comment]
Added following:
#82B1FF as Blue_A100
#185ABC as ~user_03
#008577 as Teal_deep_500
#1565C0 as  Blue_800
