### ISSUE TITLE
Contact detail improperly themed

### ISSUE THREAD

**Issue by mblob** [SpiritCroc/DarkCroc-Android-theme#4]
Contact detail fields are using white font on white background 
![Ex](https://i.imgur.com/uZljXRz.png)

**Comment by SpiritCroc** [comment]
Fine here. I can't help without further information, please check https://github.com/SpiritCroc/DarkCroc-Android-theme/blob/9.0-substratum/about.md

**Comment by mblob** [comment]
Sorry for the lack of detail
Phone: xiaomi poco f1
Rom: syberiaos v2.1
Rom has substratum support : yes
Substratum version: 1015
Android version: 9
DarkCroc version : 1.1
Overlay used: contact (1.7.31)

**Comment by SpiritCroc** [comment]
Apparently your ROM ( https://github.com/syberia-project/manifest ) uses the same source code for contacts like mine ( https://github.com/AICP/platform_manifest ).
Since I cannot reproduce this is, please make sure no other overlays are installed and active (from other Substratum themes or overlays coming with your ROM), you have recompiled and reactivated the latest overlays for this theme and your ROM version, and rebooted your device after that.
If this doesn't help, I'm clueless at the moment.

**Comment by mblob** [comment]
Syberia ROM get suspended so I switched to caf reloaded, theme is now applying properly. So it was ROM related.
