### ISSUE TITLE
Android Q support

### ISSUE THREAD

**Issue by dimqua** [SpiritCroc/DarkCroc-Android-theme#8]
~~Does your theme work on Android 10?~~

**Comment by dimqua** [comment]
I figured it out. It works in general, but I can't build 4 overlays: `com.android.phone` (dialer), `com.android.packageinstaller`, `com.android.documentsui` and Magisk manager. The latter 3 are dark by default. Dialer isn't. :(

[link](https://user-images.githubusercontent.com/540898/68283778-3eaaef80-008d-11ea-97de-bd0056d561c2.png)

 I'm using LOS 17, [substratum lite](https://play.google.com/store/apps/details?id=projekt.substratum.lite&hl=en) and Magisk.

**Comment by dimqua** [comment]
Another issue. Few icons are missing, and the background is black, not dark gray.

[link](https://user-images.githubusercontent.com/540898/68283285-546be500-008c-11ea-9442-c38c5510429e.png)

**Comment by dimqua** [comment]
According to the devs: _substratum beta "not lite" update works on Q_. Root is required, ofc.

https://www.xda-developers.com/substratum-android-10-theming/

**Comment by SpiritCroc** [comment]
I currently don't plan on supporting Android 10, as it does not make much sense to me considering the inbuilt dark theme from AOSP.

Missing from the AOSP dark theme are some apps like phone, contacts and messaging.
DocumentsUI and PackageInstaller should already be dark from the AOSP theme.
Contacts and Messaging haven't changed much since P, so the overlays still should work (they do for me on AICP). For AOSP dialer, there were attempts to introduce a dark theme from AOSP, but this is unfortunately not yet functional and breaks the old DarkCroc overlay at the same time.

I have created an updated dark theme for dialer for the inbuilt theming of the AICP custom ROM (which did include themes generated from Default Dark and DarkCroc before). This is incompatible with Android 9 ROMs though (as in: it won't compile). So I would have to release a new theme just for this app or deal with variants that many users won't get and message me with compile errors again.

So for now, I'm still theming Android 10 to my likings / similar to how Default Dark and DarkCroc looked, but only for the AICP inbuilt theming for now, which also save me from troubles of supporting ROMs that do their own stuff again etc. With the current possibilities of theming AOSP from the custom ROM perspective, and the finally implemented system wide dark mode (did you know you can force any app to be dark from the developer settings?), I don't really see the need for Substratum on my device anymore.

**Comment by dimqua** [comment]
OK, I understand. Could you please fix the issue with missing icons in settings? IIRC, there's a similar problem with LOS 16.

> did you know you can force any app to be dark from the developer settings?

Thanks for the info!

**Comment by SpiritCroc** [comment]
I pushed a commit for new dashboard icons in Q here: https://github.com/SpiritCroc/DarkCroc-Android-theme/commit/840a975f96bcbc82e62567496a6349c245572a5c

Do you build yourself and can test, or do you prefer me to push an update?

I did not find the missed icons in lineage 16.0. If you can tell me which ones exactly, I can look into those again.

**Comment by dimqua** [comment]
Works for me, thanks. But I'd prefer to have dark gray background in settings rather than black. Is it possible for you to change that?

Meanwhile I've an another problem. When you enable system UI overlay and dark theme in AOSP settings, notifications look like this: [link](https://user-images.githubusercontent.com/540898/68349185-4d38eb80-010d-11ea-9ba5-98ff6931259d.png) I do not have such issue with other themes.

**Comment by SpiritCroc** [comment]
As said before, I won't support Android 10 with this theme, maybe that icon patch sent a wrong sign.

Due to the implementation of the dark system theme in AOSP, enough has changed to justify recreating the theme from scratch for the concerned parts like Settings, SystemUI etc. (which is what I'm doing for AICP in a more customizable way than Substratum exposures even allow).
So for supporting Android 10, I'd basically need to provide a successor theme again, or deal with variants again to make it compile for each Android version, which users tend to have problems with. Unfortunately, the Substratum team has not really reacted to my proposal of automatic overlay variants per Android version back in 2017.

For the optimal DefaultDark / DarkCroc experience in Android 10, the way to go is using AICP. I can do things there that I can't with overlays.

I see that you forked the theme, so if you feel like updating the substratum theme to Android 10 (I recommend to use a new branch and a new package name for dropping Android 9 support), you can see what I did for AICP on our github https://github.com/AICP/packages_overlays_AICP/tree/q10.0 and on our gerrit https://gerrit.aicp-rom.com/q/topic:qs-themes+OR+topic:10_themes+OR+topic:theme-update
